services:
  app:
    build:
      args:
        user: ethoson-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ethoson-image:latest
    container_name: ethoson-site
    expose:
      - 80:8000
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./database:/var/www/database
    networks:
      - ethoson-network
  nginx:
    image: nginx:alpine
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - ethoson-network
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -W /var/www/certbot --keep-until-expiring --email ${EMAIL_DEPLOY} -d ${SITE_DEPLOY} --agree-tos
networks:
  ethoson-network:
    driver: bridge