services:
  app:
    build:
      args:
        user: ethoson-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ethoson-image:latest
    container_name: ethoson-site
    restart: unless-stopped
    working_dir: /var/www/
    expose:
      - 9000
    volumes:
      - ./:/var/www
      - ./database:/var/www/database
    networks:
      - ethoson-network
  caddy:
    image: caddy:2.7-alpine
    container_name: caddy-container
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - ethoson-network
networks:
  ethoson-network:
    driver: bridge